version: '3.7'

services:

  app:
    image: app
    build:
      context: .
    user: $UID:$GID
    command: python /app/src/manage.py runserver 0.0.0.0:8000
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - ./:/app/
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:11.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  postgres_data:
